#!/bin/bash

clear
# banner
echo
echo
echo "===============  HUMMINGBOT DASHBOARD ==============="
echo
echo
echo "ℹ️  Press [ENTER] for default values:"
echo
echo

read -p "Enter the branch to be clone (default: main) >> " github_branch
read -p "Enter folder name (default: dashboard) >> " github_folder 

[[ $github_branch == "" ]]  && github_branch="main"
[[ $github_folder == "" ]] && github_folder="dashboard"

look_for_dir (){
    # this function look for directory first and creates the folder if available
    if [[ $github_folder == "" ]]
    then 
        x=0 ; folder_exist=false
        while [ $folder_exist == false ]
            do 
                if [ $x == 0 ]; then
                    github_folder="dashboard"
                else
                    github_folder="dashboard($x)"
                fi

                if [ -d "$PWD/$github_folder" ]; then 
                    x=$((x + 1)) # increments the default folder
                else
                    folder_exist=true
                fi
        done 
    fi
}; look_for_dir

proceed_installation (){
    git clone -b $github_branch https://github.com/hummingbot/dashboard $github_folder
    cd $github_folder # move to dashboard directory
    display_commit=$(git log | head -5 | grep commit | sed 's/commit //') 
    conda env remove -n dashboard # remove dashboard env
    conda env create -f environment_conda.yml # create dashboard env 
    source "${CONDA_BIN}/activate" dashboard # activate dashboard
    [[ $CONDA_PREFIX == "dashboard" ]] && echo "Dashboard activated!"

    echo
    echo "===============  DASHBOARD SETUP COMPLETED ==============="
    echo
    echo
    echo "ℹ️  Repository: $github_repo"
    echo "ℹ️  Branch: $github_branch"
    echo "ℹ️  Commit: $display_commit"
    echo
    echo

    read -p "Do you want to run Dashboard? (default: yes) >> " check_start
    if [[ $check_start == "Yes" ]] || [[ $check_start == "y" ]] || [[ $check_start == "Y" ]] || [[ $check_start == "yes" ]] || [[ $check_start == "" ]]; then
        echo "Dashboard is loading now.." 
        streamlit run main.py # start Hummingbot client 
    fi
}


echo 
echo "Repository: https://github.com/hummingbot/dashboard"
echo "Checkout branch: $github_branch"
echo "Directory: $PWD/$github_folder"
read -p "Proceed? (default: yes) >> " github_next
echo

if [[ $github_next == "Yes" ]] || [[ $github_next == "y" ]] || [[ $github_next == "Y" ]] || [[ $github_next == "yes" ]] || [[ $github_next == "" ]]
then 
    proceed_installation
else
    echo
    echo "Exiting setup since invalid answer! try again later"
    echo 
    exit 1
fi
