#!/bin/bash


check_image (){
    local ci_image=("$@")
    for i in "${ci_image}"; do
        echo "$i"
    done
}

c_array=("test" "testt" "testtt")
check_image "${c_array[@]}"

# Test >> hello world