#!/bin/bash

# conda activate dashboard 
# Open the Python terminal
clear
read -p "Enter dashboard password (default: t3st1) >> " get_password
hash_make=$(python -c "import streamlit_authenticator as stauth; print(stauth.Hasher(['$get_password']).generate())")
hash_password=$(echo "$hash_make" | grep -oE '\$2b\$\d{2}\$[./A-Za-z0-9]{53}' | sed 's/^\$//')
yq eval --in-place '.credentials.usernames.admin.password = strenv(hash_password)' credentials.yml
echo $hash_password