#!/bin/bash

error_message=$(git clone -b asdas https://github.com/hummingbot/hummmingbot 2>&1)
echo -e "(date +'%Y-%m-%d %H:%M:%S'): $error_message\n" 2>> test.log



# edit_logs (){
#     d=$(cat test.log)
#     echo -e "$d\n$(date +'%Y-%m-%d %H:%M:%S'): asdasdasd \n" > test.log
# }; edit_logs