version: "3.9"
services:
  bot:
    image: hummingbot/hummingbot:development
    container_name: ralph
    volumes:
      - "/$folder/conf:/conf"
      - "/$folder/logs:/logs"
      - "/$folder/data:/data"
      - "/$folder/scripts:/scripts"
      - "/$folder/certs:/certs"
    environment:
      - CONFIG_PASSWORD=test
      - CONFIG_FILE_NAME=log_price_example.py
    logging:
      driver: "json-file"
      options:
          max-size: "10m"
          max-file: 5
    tty: true
    stdin_open: true
    network_mode: host