#!/bin/bash

# Script for creating docker image docker postgres

clear

echo "Press enter to default"
read -p "Do you want to create a customize database? (default: no) >> " docker_prompt

if [[ $docker_prompt == '' ]]; then
    echo
    docker run --name postgres-db \
    -e POSTGRES_PASSWORD=docker \
    -e POSTGRES_DB=test_db \
    -e POSTGRES_USER=user \
    -d -p 5432:5432 \
    postgres

    echo
elif [[ $docker_prompt == "Yes" || $docker_prompt == "yes" ]]; then
    echo
    read -p "Enter name of docker image (default: postgress-db) >> " docker_img_name
    read -p "Enter name of database (default: test_db) >> " docker_dbname
    read -p "Enter password of database (default: docker) >> " docker_password
    read -p "Enter username (default: user) >> " docker_user 
    echo
else
    echo -e "\nScript only accepts yes or no, please relaunch the script again\n"
    exit 1
fi





